# jer ar dadebula davaleba!!!!!!!!!!!!!!!!!!
# jer ar dadebula davaleba!!!!!!!!!!!!!!!!!!
# jer ar dadebula davaleba!!!!!!!!!!!!!!!!!!
# jer ar dadebula davaleba!!!!!!!!!!!!!!!!!!
# jer ar dadebula davaleba!!!!!!!!!!!!!!!!!!
# jer ar dadebula davaleba!!!!!!!!!!!!!!!!!!
# jer ar dadebula davaleba!!!!!!!!!!!!!!!!!!
# jer ar dadebula davaleba!!!!!!!!!!!!!!!!!!
# jer ar dadebula davaleba!!!!!!!!!!!!!!!!!!
# jer ar dadebula davaleba!!!!!!!!!!!!!!!!!!
# jer ar dadebula davaleba!!!!!!!!!!!!!!!!!!
# jer ar dadebula davaleba!!!!!!!!!!!!!!!!!!
# jer ar dadebula davaleba!!!!!!!!!!!!!!!!!!
# jer ar dadebula davaleba!!!!!!!!!!!!!!!!!!
# jer ar dadebula davaleba!!!!!!!!!!!!!!!!!!
# jer ar dadebula davaleba!!!!!!!!!!!!!!!!!!
# jer ar dadebula davaleba!!!!!!!!!!!!!!!!!!
# jer ar dadebula davaleba!!!!!!!!!!!!!!!!!!
# jer ar dadebula davaleba!!!!!!!!!!!!!!!!!!
# jer ar dadebula davaleba!!!!!!!!!!!!!!!!!!
